### ISSUE TITLE
colors.color(string) not working when using with Grunt

### ISSUE THREAD

**Issue by mgingras** [Marak/colors.js#102]
Running a nodejs application through Grunt I noticed that strings colored using color(string) were not colored, however, by using string.color the color was picked up.

**Comment by pksunkara** [comment]
Since, the stdout is not a TTY, colors will be disabled. Check the code [here](https://github.com/Marak/colors.js/blob/master/lib/system/supports-colors.js#L40). I assume that grun takes the output from colors and then prints it. You must use `colors.enabled` option once you require this module to enable colors even though the stdout is not a TTY.

**Comment by Marak** [comment]
@pksunkara - You should review the code path for supports colors and https://github.com/Marak/colors.js/blob/master/lib/extendStringPrototype.js to ensure that colors support is being correctly applied to both APIs.

It would also be good to add test coverage for this.

**Comment by pksunkara** [comment]
I actually merged a fix related to this in https://github.com/Marak/colors.js/pull/97

**Comment by pksunkara** [comment]
@mgingras Related to what @Marak was saying, both the stringPrototype and the normal api works the same now, both shouldn't be printing colors now. I guess my first comment can be confusing without this context.

So, if you want colors to be printed for either of the api, you need to use the `enabled` option.
