### ISSUE TITLE
What's "code.closeRe" doing in color.js?

### ISSUE THREAD

**Issue by BookSong** [Marak/colors.js#147]
In './lib/colors.js', there is this line:

``` javascript
str = code.open + str.replace(code.closeRe, code.open) + code.close;
```

located here:

``` javascript
function applyStyle() {
  ...
  var i = nestedStyles.length;
  while (i--) {
    var code = ansiStyles[nestedStyles[i]];
    str = code.open + str.replace(code.closeRe, code.open) + code.close;
  }
  ...
}
```

But it doesn't seem to do much.

I suppose it means to prevent nested style calls from closing a style too early, but what is the point of that, if every part of the string processed always get the same depth of nesting?

Can anyone tell?

**Comment by very** [comment]
I'm not 100% sure how the API works yet but that line is really doing good things.

For example let's assume you want to have the string `'colored'` in red. You can do this in many ways:

    var colored = 'colored'.red;
    assert(colored === colors.stylize('colored', 'red');
    assert(colored === colors.red('colored');

There are differences though. Only the last way makes use of the line you've mentioned.

So now assume you want to use it in an green string:
`('Hello ' + 'colored'.red + ' world!').strip.green` makes the whole string green.
`('Hello ' + 'colored'.red + ' world!').green` makes `'colored'` red and `'Hello '` green.
`colors.green('Hello ' + 'colored'.red + ' world!')` makes `'colored'` red and both `'Hello '` and `' world!'` green because the color stop code of `'colored'.red` gets replaced with a green color start code.

**Comment by DABH** [comment]
Thanks for the interesting discussion!
