### ISSUE TITLE
Can I use color.js in Webstorm ?

### ISSUE THREAD

**Issue by HaloWang** [Marak/colors.js#156]
How can I make color.js enable in WebStorm?

**Comment by simonhochrein** [comment]
hello,
I have used this library with WebStorm. 
The WebStorm terminal should work.
What version are you using?

**Comment by HaloWang** [comment]
Thanks,
The latest version of color.js
Yes, it work in WS - terminal tab.
But not 'Run' tab 😰

<img width="542" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7344724/14338320/b1c0b79e-fca8-11e5-8e07-99ada067a814.png">

**Comment by simonhochrein** [comment]
I have tested and get the same results...
I think that WebStorm only supports highlighting errors in the run tab..
Also, (This is unnecessary) what theme are you using?

**Comment by HaloWang** [comment]
@simonhochrein 
😂 It's not a theme, just search "antialiasing" and "override default fonts" in the preferences of WebStorm.

**Comment by simonhochrein** [comment]
OHH ok thanks! :smiley:

**Comment by Tomino2112** [comment]
Something funny is happening in the "Run" tab in jetbrains IDEs. As mentioned above, colors work in console but not in run tab **BUT** that is when you run your node app locally. If I configure remote node interpreter (from a VM) the colors work in Run tab as well.

Local node interpreter:
![2016-05-18_221307](https://cloud.githubusercontent.com/assets/1140217/15375214/cec68554-1d45-11e6-80f1-75945438405b.jpg)

Remote Interpreter:
![2016-05-18_221248](https://cloud.githubusercontent.com/assets/1140217/15375221/db244304-1d45-11e6-8c6a-95575c7a2062.jpg)

**Comment by Irrelon** [comment]
I created a pull request to fix issues like this in WebStorm and other JetBrains IDE's. https://github.com/Marak/colors.js/pull/150 it hasn't been merged yet though :(

**Comment by Irrelon** [comment]
I created a new npm module which is EXACTLY the same as colors except it includes my fix for webstorm. You can use it as a drop-in replacement for colors:

```bash
npm install irrelon-colors
```

In webstorm, edit your run configuration:

<img width="179" alt="screen shot 2016-06-20 at 10 45 05" src="https://cloud.githubusercontent.com/assets/492293/16189807/2459696c-36d4-11e6-9076-f141e2ad7b5d.png">

Then click ... next to the Environment variables section:

<img width="693" alt="screen shot 2016-06-20 at 10 46 32" src="https://cloud.githubusercontent.com/assets/492293/16189844/4926186c-36d4-11e6-8f64-a1596e9f0df3.png">

Then click +

<img width="83" alt="screen shot 2016-06-20 at 10 46 56" src="https://cloud.githubusercontent.com/assets/492293/16189859/57075dba-36d4-11e6-9eae-47197b50bf41.png">

Define a new variable called "ALLOW_COLORS" and set the value to true:

<img width="465" alt="screen shot 2016-06-20 at 10 47 27" src="https://cloud.githubusercontent.com/assets/492293/16189883/6fc8ca82-36d4-11e6-9645-8a39e3497f5a.png">

That's it. Now colors will show up when using irrelon-colors as a drop-in replacement for colors.

P.S. I wish I didn't have to make a fork and publish the fork but it's been quite a while since I made the pull request to fix this issue and had no movement on it for some time, so I created irrelon-colors on npm so that I have colorful output until the real repo can merge in the change.

**Comment by Tomino2112** [comment]
@Irrelon Great job! Since you didn't need Jetbrain fix, is this more of a colors package fix? Maybe it would be better/faster to create pull request there

**Comment by Irrelon** [comment]
@Tomino2112 I already created a pull request on colors: https://github.com/Marak/colors.js/pull/150 it was back in February and didn't get a response yet :(

**Comment by Tomino2112** [comment]
@Irrelon Ah, sorry, for some reason I thought you created request on webstorm repo... Nothing left to do then, just hope someone will merge it

**Comment by Irrelon** [comment]
@Tomino2112 Indeed, I really love this package, it's so simple and elegant but it looks a little under-loved recently. I totally understand that keeping a package like this updated and responding to pull requests & issues can be quite time consuming, having my own (relatively) popular package (https://github.com/Irrelon/ForerunnerDB). If the admins are having trouble keeping up or have time constraints, I'm sure that someone else would be able to lend some time to it!

**Comment by Alexsey** [comment]
I was having issues with different terminals with this module also with WebStorm's terminal. To solve them you need to do two things:
1. Before loading `colors` execute code 
`process.stdout.isTTY = true`
2. Require like
`require('colors').enabled = true`

Specifically WebStorm requires second thing. For example Windows Git-Bash requires first

**Comment by segrey** [comment]
@Marak please update `lib/system/supports-colors.js` to supports-color >= 2.0.0. That would fix this issue, as colors would be enabled via FORCE_COLOR environment variable already specified by WebStorm and other JetBrains IDEs.
Another workaround could be to add `--colors` to `Application parameters` field in Node.js run configuration.

**Comment by clouless** [comment]
This project works fine in run tab of Webstorm: https://github.com/medikoo/cli-color

**Comment by Boorj** [comment]
@Alexsey, thanks, that helped

**Comment by DABH** [comment]
How does it work now with `colors@next`?  We've updated `supports-color`, so this should be working now!  Would love it if someone could let me know!

**Comment by ViieeS** [comment]
@DABH it works! I've tested it in PHPStorm, should work in WebStorm too.

**Comment by DABH** [comment]
Awesome, thanks for checking! I’m going to close this issue has resolved, feel free to open new issue if there are still problems —  but seems like we figured this one out.
