### ISSUE TITLE
Compatibility warning

### ISSUE THREAD

**Issue by lnwdr** [Marak/colors.js#170]
There should be a warning about how this library might interact with others when used in its default mode (the "super nifty") one.

The statement "If you are writing good code you will never have an issue with the first approach." is not only quite questionable (what is "good code" exactly? who defines that?) but also ignores that many JS projects these days have up to hundreds of dependencies, most of them only depended upon indirectly via another dependency. Modifying the global prototypes becomes very risky in this scenario.

This particular case for example breaks String iteration in some libraries. I only stumbled over this because `union`, an http library that is totally unrelated to color shell output, crashes in certain cases because of the extra properties on the String prototype. I did not require `union` in my project directly, I was using `http-server` which then uses `union` and `colors`. (Yes, I also submitted a fix to the `http-server` project).

Please, add a reasonable warning in the README about this. I personally would prefer the "safe" mode to be the default but a warning is a good start.

**Comment by Marak** [comment]
Considering I'm the original creator and author of `http-server`, it's sad to see how its broken now.

Regardless, this isn't my problem and also I don't care. My personal preference is not to allow any libraries in my entire dependency tree to iterate through strings, ever. `colors` usually lets me know if someone messed up down the chain because Zalgo is summoned.

FYI, `union` looks outdated by over two years. Probably should switch to something new.
