### ISSUE TITLE
toUpperCase transforms color code to transparent

### ISSUE THREAD

**Issue by MartinMuzatko** [Marak/colors.js#177]
Using `toUpperCase()` at the end of a string, displays the line as transparent.

Example:

``` js
console.error(colors.red('ENVIRONMENT NOT SET FOR UPLOAD TO '+theme).toUpperCase())
```

![image](https://cloud.githubusercontent.com/assets/2950505/20829987/d83564fa-b87e-11e6-921e-d84dec2eac33.png)

I even tried it in a semi-transparent terminal:

![image](https://cloud.githubusercontent.com/assets/2950505/20829991/dc29fdc8-b87e-11e6-86ee-5fb075ce6f9c.png)

**Comment by DABH** [comment]
True, but not a bug with colors.  Seems like Node.js' toUpperCase and toLocaleUpperCase etc. will manipulate the case of parts of ASCII escape sequences.  e.g. [31m (correct) becomes [31M (wrong).  So the issue is those JS string functions aren't aware of ASCII escape sequences.  There's very little discussion online about this, but one could consider opening an issue with the node folks.  The other obvious alternative is to do your case manipulation before colorizing, and everything works fine.  Thanks for bringing this up, and sorry there's not more we can do on this!
