### ISSUE TITLE
Boolean values return undefined 

### ISSUE THREAD

**Issue by eperry** [Marak/colors.js#209]
I believe this to be a bug/unhandled issue with colors

If you use"colors" on boolean values it comes back as undefined not true.{color}  or "false.".{color}

> var colors = require('colors')
> var isTrue = true
> console.log("isTrue ",isTrue)
> console.log ("isTrue ".red,isTrue.green)

![screenshot from 2018-02-03 17-14-54](https://user-images.githubusercontent.com/6170692/35772070-ecce4bf6-0905-11e8-93a3-51050ef6ac2a.png)

I know how to deal with this with an if statement but believe since this is a Language defined type, it should be handled within colors

**Comment by 22nds** [comment]
Maybe this will help you.
```
console.log(colors.red("isTrue "), colors.green(isTrue));
```

**Comment by DABH** [comment]
The nifty way of using colors extends String prototypes, but not Boolean prototypes; so as the above commenter suggested you have to use the non-nifty way to bools.  We'd welcome a PR to extend the Boolean class in a similar way as Strings; but otherwise I'll close this issue for now since there is a standard way of handling this already.  Thanks!
