### ISSUE TITLE
If you want money you are at a wrong platform

### ISSUE THREAD

**Issue by AShao0425** [Marak/colors.js#339]
Open source is a term that originally referred to open source software (OSS). Open source software is code that is designed to be publicly accessible—anyone can see, modify, and distribute the code as they see fit. You are using GitHub and you intentionally planned to make it open source, and just out of sudden you became agitative? So short of money? If you want money go find yourself an actual company, you are at the wrong platform, go [sellcode.com](sellcode.com).

**Comment by v01dXYZ** [comment]
I think you don't understand that he didn't become suddenly agitative. He slowly burned out because of overworking on its day job and its open source "hobbies". Sure, Marak is not doing well currently emotionally for personal reasons.
Now, you have to remember that's not the first maintainer that threw the towel citing a OSS project that has become a full-time job. He simply did it the most provocative way, to show how much "actual companies" depends on its hobby code. Please, let's talk about the elephant in the room, OSS sustainability and  the lack of investment from corporates.

**Comment by AShao0425** [comment]
> I think you don't understand that he didn't become suddenly agitative. He slowly burned out because of overworking on both its day job and its open source "hobbies". Sure, Marak is not currently doing well emotionally for personal reasons.
> Now, you have to remember that's not the first maintainer that threw the towel citing a OSS project that has become a full-time job. He simply did it the most provocative way, to show how much "actual companies" depends on its hobby code. Please, let's talk about the elephant in the room, OSS sustainability and  the lack of investment from corporate.

The point I am not getting is that why he doesn't use his code to prove those companies on his efforts which would possibly assign him a job accordingly so he will still have chance of maintaining his projects. But instead he used a more of a extreme way to express his feeling.

**Comment by v01dXYZ** [comment]
Thank for making your point of view clearer and more articulated. Your initial comment was like saying "Marak is a crying baby that could not find a real job" which could be a little bit insulting meanwhile your second one was "I think he was too extreme and that won't help the packages to get better maintain" which is much more helpful as a comment.
